{
 "title": "Kemal",
 "description": "test",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Exceptions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(http_request_exceptions_total[10m])",
     "legendFormat": "{{exception}} '{{path}}'"
    }
   ]
  },
  {
   "title": "GC Total Bytes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "increase(process_gc_total_bytes[5m])",
     "legendFormat": "GC Total Bytes"
    }
   ]
  },
  {
   "title": "Total HTTP requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(http_requests_total[30s])",
     "legendFormat": "{{method}} {{code}} {{path}}"
    }
   ]
  },
  {
   "title": "HTTP Response Time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_bucket[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "5m HTTP Operator",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(http_requests_total) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  }
 ]
}